name: Deploy to DigitalOcean (Bun)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

    - name: Deploy to Droplet
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        ACTIVITY_URL: ${{ secrets.ACTIVITY_URL }}
      run: |
        ssh user@your-droplet-ip << 'EOF'
        export CLIENT_ID=$CLIENT_ID
        export TOKEN=$TOKEN
        export ACTIVITY_URL=$ACTIVITY_URL
        bash /var/www/app1/deploy.sh
        EOF
